POST http://localhost:3001/contenido
Content-Type: application/json

{
      "id": 3,
      "poster": "./posters/3.jpg",
      "titulo": "The Mandalorian",
      "categoria": "Serie",
      "genero": "Sci-Fi, Fantasía, Acción",
      "gen": "Ciencia Ficción",
      "busqueda": "The Mandalorian, Sci-Fi, Fantasía, Suspenso, Pedro Pascal, Carl Weathers, Misty Rosas, Chris Bartlett, Rio Hackford, Giancarlo Esposito",
      "resumen": "Ambientada tras la caída del Imperio y antes de la aparición de la Primera Orden, la Serie sigue los pasos de un pistolero solitario en las aventuras que protagoniza en los confines de la galaxia, donde no alcanza la autoridad de la Nueva República.",
      "temporadas": 2,
      "reparto": "Pedro Pascal, Carl Weathers, Misty Rosas, Chris Bartlett, Rio Hackford, Giancarlo Esposito",
      "trailer": "https://www.youtube.com/embed/aOC8E8z_ifw"
}

###

PATCH  http://localhost:3001/contenido/1
Content-Type: application/json

{
 
 "titulo":"3000"
  
            
}

###
DELETE http://localhost:3000/contenido/1