POST http://localhost:3001/contenido
Content-Type: application/json

{
      "id": 7,
      "poster": "./posters/7.jpg",
      "titulo": "Guasón",
      "categoria": "Película",
      "gen": "Suspenso",
      "genero": "Crimen, Suspenso",
      "busqueda": "Guasón, The Joker, Crimen, Suspenso, Drama, DC Comics, Joaquin Phoenix, Robert De Niro, Zazie Beetz, Frances Conroy, Brett Cullen, Shea Whigham",
      "resumen": "Arthur Fleck (Phoenix) es un hombre ignorado por la sociedad, cuya motivación en la vida es hacer reír. Pero una Serie de trágicos acontecimientos le llevarán a ver el mundo de otra forma. Película basada en el popular personaje de DC Comics Joker, conocido como archivillano de Batman, pero que en este film tomará un cariz más realista y oscuro.",
      "temporadas": "N/A",
      "duracion": "97 minutos",
      "reparto": "Joaquin Phoenix, Robert De Niro, Zazie Beetz, Frances Conroy, Brett Cullen, Shea Whigham",
      "trailer": "https://www.youtube.com/embed/zAGVQLHvwOY"
}

###

PATCH  http://localhost:3001/contenido/4
Content-Type: application/json

{
 
 "titulo":"salve jebus"
  
            
}

###
DELETE http://localhost:3001/contenido/1