POST http://localhost:3001/contenido
Content-Type: application/json

{
      "id": 4,
      "poster": "./posters/4.jpg",
      "titulo": "The Umbrella Academy",
      "categoria": "Serie",
      "gen": "Ciencia Ficción",
      "genero": "Sci-Fi, Fantasía, Drama",
      "busqueda": "The Umbrella Academy, Sci-Fi, Fantasía, Drama, Tom Hopper, David Castañeda, Emmy Raver-Lampman, Robert Sheehan, Aidan Gallagher, Elliot Page",
      "resumen": "La muerte de su padre reúne a unos hermanos distanciados y con extraordinarios poderes que descubren impactantes secretos y una amenaza que se cierne sobre la humanidad.",
      "temporadas": 1,
      "reparto": "Tom Hopper, David Castañeda, Emmy Raver-Lampman, Robert Sheehan, Aidan Gallagher, Elliot Page",
      "trailer": "https://www.youtube.com/embed/KHucKOK-Vik"
}

###

PATCH  http://localhost:3001/contenido/1
Content-Type: application/json

{
 
 "titulo":"3000"
  
            
}

###
DELETE http://localhost:3000/contenido/1